---
trigger:
  branches:
    include:
      - master
  tags:
    include:
      - "*"
    exclude:
      - untagged*
pr:
  - master

# variables:
#   VERSION_HADOLINT: "latest"
#   VERSION_SHELLCHECK: "latest"

jobs:
  - job: "hadolint"
    pool:
      vmImage: "ubuntu-16.04"
    container: pipelinecomponents/hadolint:latest
    steps:
      - script: |
          hadolint --version
          hadolint "${TARGET}/Dockerfile"
        displayName: "Run hadolint"

  - job: "shellcheck"
    pool:
      vmImage: "ubuntu-16.04"
    container: pipelinecomponents/shellcheck:latest
    steps:
      - script: |
          shellcheck --version
          apk --no-cache add grep
          find . -type f -print0 | \
            xargs -0 sed -i 's:#!/usr/bin/with-contenv bash:#!/bin/bash:g'
          for file in $(grep -IRl "#\!\(/usr/bin/env \|/bin/\)" --exclude-dir ".git" "${TARGET}"); do
            if ! shellcheck $file; then
              export FAILED=1
            else
              echo "$file OK"
            fi
          done
          if [ "${FAILED}" = "1" ]; then
            exit 1
          fi
        displayName: "Run shellcheck"
