---
trigger:
  branches:
    include:
      - master
  tags:
    include:
      - "*"
    exclude:
      - untagged*
pr:
  - master

variables:
  ENABLE_PREFLIGHT_ESLINT: "true"
  ENABLE_PREFLIGHT_HADOLINT: "false"
  ENABLE_PREFLIGHT_MARKDOWNLINT: "true"
  ENABLE_PREFLIGHT_SHELLCHECK: "false"
  ENABLE_PREFLIGHT_YAMLLINT: "true"
  VERSION_ESLINT: "latest"
  VERSION_HADOLINT: "latest"
  VERSION_MARKDOWNLINT: "latest"
  VERSION_SHELLCHECK: "latest"
  VERSION_YAMLLINT: "latest"

jobs:
  # Preflight: eslint
  - job: "Preflight: eslint"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: sudo docker pull sherpany/eslint:${VERSION_ESLINT}
        displayName: "Install eslint"
      - script: |
          if [ ${ENABLE_PREFLIGHT_ESLINT} = "true" ]; then
            sudo docker run --rm -i \
              -v $(pwd):/app/js:ro sherpany/eslint:${VERSION_ESLINT} .
          else
            echo "eslint disabled. Skipping.."
          fi
        displayName: "Run eslint"
  # Preflight: hadolint
  - job: "Preflight: hadolint"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: sudo docker pull hadolint/hadolint:${VERSION_HADOLINT}
        displayName: "Install hadolint"
      - script: |
          if [ ${ENABLE_PREFLIGHT_HADOLINT} = "true" ]; then
            sudo docker run --rm -i \
              -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
              hadolint/hadolint:${VERSION_HADOLINT} < Dockerfile
          else
            echo "hadolint disabled. Skipping.."
          fi
        displayName: "Run hadolint"
  # Preflight: markdownlint
  - job: "Preflight: markdownlint"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: sudo docker pull mivok/markdownlint:${VERSION_MARKDOWNLINT}
        displayName: "Install markdownlint"
      - script: |
          if [ ${ENABLE_PREFLIGHT_MARKDOWNLINT} = "true" ]; then
            sudo docker run --rm -i \
              -v $(pwd):/data:ro mivok/markdownlint:${VERSION_MARKDOWNLINT} .
          else
            echo "markdownlint disabled. Skipping.."
          fi
        displayName: "Run markdownlint"
  # Preflight: shellcheck
  - job: "Preflight: shellcheck"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: sudo docker pull koalaman/shellcheck:${VERSION_SHELLCHECK}
        displayName: "Install shellcheck"
      - script: |
          if [ ${ENABLE_PREFLIGHT_SHELLCHECK} = "true" ]; then
            sudo docker run --rm -i \
              -v $(pwd):/mnt:ro koalaman/shellcheck:${VERSION_SHELLCHECK} *.sh
          else
            echo "shellcheck disabled. Skipping.."
          fi
        displayName: "Run shellcheck"
  # Preflight: yamllint
  - job: "Preflight: yamllint"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: sudo docker pull sdesbure/yamllint:${VERSION_YAMLLINT}
        displayName: "Install yamllint"
      - script: |
          if [ ${ENABLE_PREFLIGHT_YAMLLINT} = "true" ]; then
            sudo docker run --rm -i \
              -v $(pwd):/yaml:ro \
              sdesbure/yamllint:${VERSION_YAMLLINT} yamllint .
          else
            echo "yamllint disabled. Skipping.."
          fi
        displayName: "Run yamllint"
