---
trigger:
  branches:
    include:
      - master
  tags:
    include:
      - "*"
    exclude:
      - untagged*
pr:
  - master

variables:
  ENABLE_HADOLINT: "false"
  ENABLE_SHELLCHECK: "false"
  VERSION_HADOLINT: "latest"
  VERSION_SHELLCHECK: "latest"

jobs:
  # hadolint
  - job: "hadolint"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: sudo docker pull hadolint/hadolint:${VERSION_HADOLINT}
        displayName: "Install hadolint"
      - script: |
          if [ ${ENABLE_HADOLINT} = "true" ]; then
            sudo docker run --rm -i \
              -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
              hadolint/hadolint:${VERSION_HADOLINT} < Dockerfile
          else
            echo "hadolint disabled. Skipping.."
          fi
        displayName: "Run hadolint"
  # shellcheck
  - job: "shellcheck"
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: sudo docker pull koalaman/shellcheck:${VERSION_SHELLCHECK}
        displayName: "Install shellcheck"
      - script: |
          if [ ${ENABLE_SHELLCHECK} = "true" ]; then
            sudo docker run --rm -i \
              -v $(pwd):/mnt:ro koalaman/shellcheck:${VERSION_SHELLCHECK} *.sh
          else
            echo "shellcheck disabled. Skipping.."
          fi
        displayName: "Run shellcheck"
